language: php
php:
  - 5.4

before_install:
  - sudo apt-get update -qq > /dev/null 2>&1
  - sudo apt-get install php5 php-pear
  - sudo pear channel-update pear.php.net
  - sudo pear install phpunit/PHPUnit

script: phpunit Test