language: php
php:
  - 5.4
  - 5.5

services:
  - mongodb

before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'passwd';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON  test.* TO 'test'@'localhost';" -uroot

script: phpunit Test
