language: php
php:
  - 5.4
  - 5.5

services:
  - mongodb
  - memcached

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'passwd';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON  test.* TO 'test'@'localhost';" -uroot

script: phpunit --bootstrap LightPHP.php Test
